Fix missing return in function not returning void
This fixes a build error: 

```
error: control reaches end of non-void function [-Werror=return-type]
```